### ISSUE TITLE
Create Cognito accounts in stage environment

### ISSUE THREAD

**Issue by mjgiarlo** [LD4P/sinopia_acl#73] opened 2019-05-09 18:45 UTC
In order to test that our `sinopia_acl` task in stage is working correctly, can each person in this list create a Cognito account in stage?

Check off your name and unassign from yourself once you've created your account and changed your password. (If you're the last check/assignee, feel free to notify @rsmith11 and close the issue. Thanks!)

- [x] @mjgiarlo 
- [x] @jermnelson 
- [x] @jgreben 
- [x] @michelleif 
- [x] @ndushay 
- [x] @jmartin-sul

**Comment by jgreben** [comment] 2019-05-10 19:41
@mjgiarlo @jermnelson @michelleif How did you create a Cognito account in stage? I am getting the same error for stage that Michelle describes in https://github.com/LD4P/sinopia_acl/issues/73

**Comment by michelleif** [comment] 2019-05-10 19:44
pasting slack convo that will help:

Robert Smith [2:35 PM]
try going here:  https://sinopia-staging.auth.us-west-2.amazoncognito.com/login?response_type=token&client_id=23l30pbu74pusgh7cmtufb8d05&redirect_uri=https://stage.sinopia.io

Mike Giarlo [2:47 PM]
I created an issue to track user account creation in stage: https://github.com/LD4P/sinopia_acl/issues/73

Michelle Futornick [2:49 PM]
we have to use the sinopia-stating.auth.us… link above or via stage.sinopia.io?

Mike Giarlo [2:53 PM]
@michellef the former. stage.sinopia.io is misconfigured at the moment. (is that already ticketed, @Robert Smith? Anything I can do to help?)

**Comment by jgreben** [comment] 2019-05-10 19:51
Where are the different client ids for staging and prod being kept?

**Comment by jgreben** [comment] 2019-05-10 19:55
I was able to create an account, but cannot verify that the login works because stage has the same problem with the client id as prod.

**Comment by jmartin-sul** [comment] 2019-05-14 23:02
just created and confirmed mine.  was able to login and get what appeared to be a valid JWT for my user (decoded it and username was right, though i didn't bother checking the expiry time).

**Comment by jmartin-sul** [comment] 2019-05-14 23:03
closing and notifying @rsmith11 per the issue description...

**Closed by jmartin-sul** 2019-05-14 23:03 UTC
Labels: M3, in progress
